#!/usr/bin/env bash

# Update package list and install nginx
sudo apt-get update
sudo apt-get install -y nginx

# Create HTML files
echo "Hello World!" | sudo tee /var/www/html/index.html
echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html

# Configure Nginx redirection
redirect_config="server {
    listen 80 default_server;
    listen [::]:80 default_server;

    root /var/www/html;
    index index.html index.htm;

    location /redirect_me {
        return 301 https://www.dev.wafaa-gaafar.com;
    }

    error_page 404 /404.html;
    location = /404.html {
        root /var/www/html;
        internal;
    }
}"
echo "$redirect_config" | sudo tee /etc/nginx/sites-enabled/default > /dev/null

# Restart Nginx
sudo service nginx restart
