#!/usr/bin/env bash
# Script to display "To infinity and beyond" indefinitely with a 2-second delay between iterations.
# Displays "I am invincible!!!" when receiving a SIGTERM signal.

trap "echo 'I am invincible!!!'" SIGTERM
while :; do echo 'To infinity and beyond'; sleep 2; done
